apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: my-app
spec:
  selector:
    app: react-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort